name: Moskin
favicon: null
layout_spectrum: 0.5709421774372458
typography_spectrum: 0.9377713180147111
title: The Work of Noah Moskin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e2e3a'
    - '#a7c8f1'
    - '#a19ea5'
    - '#ffd5af'
    - '#b17459'
  brandStrength: 0.6875
  lightness: 0.00977917923592031
  saturation: 0.6805650775786489
  rhythmicContrast: 0.8253752994351089
purpose: []
